[workspace]
members = [
    "ic/libraries",
    "ic/managed/verifier",
    "rs/local-verify",
    "rs/remote-verify",
    "rs/verity-client",
    "rs/tests/load",
    "zk/host",
    "zk/guest",
]
resolver = "2"