[package]
name = "verity-verify-tls"
description = "Verity Verifier"
edition = "2021"

[dependencies]
cfg-if = "1.0.0"
elliptic-curve = { version = "0.13.8", optional = true }
p256 = { version = "0.13.2", optional = true }
serde_json = "1.0.133"
tlsn-core = { git = "https://github.com/tlsnotary/tlsn", rev = "v0.1.0-alpha.6", optional = true }
tlsn-core-no-session = { path = "../tlsn-core-no-session", optional = true }

[features]
default = ["session"]
no-session = ["dep:tlsn-core-no-session"]
session = ["dep:tlsn-core", "dep:p256", "dep:elliptic-curve"]
