[package]
name = "guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2.0", default-features = false, features = ['std'] }
verity-verify-private-transcript = { path = "../../../../../rs/verify-private-transcript" }
bincode = "1.3.3"
serde_json = "1.0.137"
zk-bench-core = { path = "../../core" }
