name: Deploy Documentation to GitHub Pages

on:
  push:
    tags:
      - 'v*.*.*' # Match semantic version tags v1.0.7

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment (if using Node.js)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16  # Replace with your project's Node.js version

    - name: Build project
      run: cd docs && bash generatedocs.sh  # Adjust based on your project's build command

    # Step 4: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.CARGO_TOKEN }}
        publish_dir: ./docs  # Replace with your build output directory
