name: Publish Rust Library to crates.io

on:
  push:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Rust toolchain
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable  # Use the stable Rust version
          override: true

      # - name: Setup crates.io Credentials
      #   run: |
      #     echo "[registries]" > $HOME/.cargo/credentials.toml
      #     echo "token = \"${{ secrets.CARGO_TOKEN }}\"" >> $HOME/.cargo/credentials.toml

      # Step 4: Publish the library
      - name: Publish Library to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
        run: |
          cd ic/libraries
          cargo publish --allow-dirty
