
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Verify-db TEST

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # or whatever version you want
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy, cargo, rustc


      - name: run Verify Test
        run: | 
          rustup update
          cargo test -- --skip async_test_example // Skip async_test_example because of its dependency on a pem file

      - name: run IC Check
        run: | 
          cd ic/managed/verifier/ &&  pnpm install &&  pnpm test:prod
      
